[package]
name = "learn-gl"
version = "0.1.0"
authors = ["oskarn <oskarn@spotify.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[dependencies]
cgmath = "0.17"
gl = "0.14"
glfw = "0.36"
image = "0.19"
tobj = "0.1.12"